import {
  ArrowElbowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUUpLeft,
  Camera,
  CalendarBlank,
  CardsThree,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartPieSlice,
  Check,
  CheckCircle,
  Coffee,
  Coins,
  CurrencyDollar,
  DotsThreeOutline,
  DownloadSimple,
  Eye,
  EyeSlash,
  Fingerprint,
  FunnelSimple,
  Gear,
  HandCoins,
  LockKey,
  MagnifyingGlass,
  Money,
  Paperclip,
  Percent,
  PiggyBank,
  Plus,
  Receipt,
  Scales,
  SquaresFour,
  Trash,
  TrendDown,
  TrendUp,
  UploadSimple,
  User,
  Warning,
  X,
} from "@phosphor-icons/react/dist/ssr";

export const ICONS = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  biometrics: Fingerprint,
  brand: Coffee,
  calendar: CalendarBlank,
  camera: Camera,
  caretDown: CaretDown,
  caretLeft: CaretLeft,
  caretRight: CaretRight,
  chart: ChartPieSlice,
  check: Check,
  checkCircle: CheckCircle,
  claim: ArrowElbowDownRight,
  close: X,
  coins: Coins,
  dashboard: SquaresFour,
  dollar: CurrencyDollar,
  dots: DotsThreeOutline,
  download: DownloadSimple,
  eye: Eye,
  eyeOff: EyeSlash,
  filings: Percent,
  filter: FunnelSimple,
  invoice: HandCoins,
  lock: LockKey,
  money: Money,
  paperclip: Paperclip,
  plus: Plus,
  receipt: Receipt,
  reserve: PiggyBank,
  scales: Scales,
  search: MagnifyingGlass,
  settings: Gear,
  transactions: CardsThree,
  trash: Trash,
  trendDown: TrendDown,
  trendUp: TrendUp,
  undo: ArrowUUpLeft,
  upload: UploadSimple,
  vendor: User,
  warning: Warning,
} as const;

export type IconName = keyof typeof ICONS;
