import {
  ArrowElbowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUUpLeft,
  Camera,
  CalendarBlank,
  CardsThree,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartPieSlice,
  Check,
  CheckCircle,
  Coffee,
  Coins,
  Gear,
  MagnifyingGlass,
  Money,
  Percent,
  PiggyBank,
  Plus,
  Receipt,
  Scales,
  SquaresFour,
  TrendDown,
  TrendUp,
  Warning,
  X,
} from "@phosphor-icons/react/dist/ssr";

export const ICONS = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  brand: Coffee,
  calendar: CalendarBlank,
  camera: Camera,
  caretDown: CaretDown,
  caretLeft: CaretLeft,
  caretRight: CaretRight,
  chart: ChartPieSlice,
  check: Check,
  checkCircle: CheckCircle,
  claim: ArrowElbowDownRight,
  close: X,
  coins: Coins,
  dashboard: SquaresFour,
  filings: Percent,
  money: Money,
  plus: Plus,
  receipt: Receipt,
  reserve: PiggyBank,
  scales: Scales,
  search: MagnifyingGlass,
  settings: Gear,
  transactions: CardsThree,
  trendDown: TrendDown,
  trendUp: TrendUp,
  undo: ArrowUUpLeft,
  warning: Warning,
} as const;

export type IconName = keyof typeof ICONS;
